import type { Metadata } from "next"
import "./globals.css"
import { Header } from "@/components/shared/Header"
import localFont from "next/font/local"

const nunito = localFont({
  src: "./fonts/Nunito.ttf",
  variable: "--font-nunito",
  weight: "400 500 600 700 800 900",
})

export const metadata: Metadata = {
  title: "Next Pizza | Главная",
  description: "Generated by create next app",
  icons: "/logo.png",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={nunito.variable}>
        <Header />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  )
}
